[package]
name = "idiomatic"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = [ "derive" ] }
serde_yaml = "0.8"
indexmap = { version = "1", features = [ "serde" ] }
thiserror = "1.0"
convert_case = "0.5"
structopt = "0.3"
